Create childOrgEnrollment
Aniket-Engg/solidity-school pull request #47
Opened 2023-02-05 13:46 UTC by amar-exe

Please check if everything is as intended in the task, if it is not LMK and I will fix it,

best regards

2023-02-08 15:52 UTC, saba8814 approved these changes
LGTM!

2023-02-10 09:00 UTC, Aniket-Engg requested changes

2023-02-10 09:00 UTC, Aniket-Engg commented on std-3/childOrgEnrollment
> +  function enroll(string memory _name, uint _age, string memory _department, string memory _childOrgName) public {
This is not actually overriding the base `enroll` method. Also, the overriding function must use the `override` keyword in the function header. Check the hint given in problem statement here: https://github.com/Aniket-Engg/solidity-school/tree/master/std-3/3_childOrgEnrollment

2023-02-27 05:41 UTC, Aniket-Engg commented
@amar-exe can you consider the requested changes?

2023-02-27 07:42 UTC, amar-exe commented on std-3/childOrgEnrollment
> +contract Enrollment {
Changed name

2023-02-27 07:42 UTC, amar-exe commented on std-3/childOrgEnrollment
> +contract NewCompany is Enrollment {
Updated

2023-02-27 08:06 UTC, amar-exe commented
@Aniket-Engg I implemented the changes, please check if everything is correct

2023-02-28 08:21 UTC, Aniket-Engg approved these changes

2023-02-28 08:21 UTC, merged

2023-02-28 13:30 UTC, amar-exe commented
@Aniket-Engg do you have any extra assignments or things that need to be done?

2023-02-28 13:39 UTC, saba8814 commented
@Aniket-Engg I'd be happy to help too, You can assign me some tasks too.